version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.0.0
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          mapping: |
            packages/common/.* common-modified true
            packages/gis-ly/.* run-gis-ly-workflow true
          config-path: .circleci/workflows.yml
